# Generated by Django 4.2.3 on 2023-07-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_tag_scope_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="scopes",
                through="articles.Scope",
                to="articles.tag",
                verbose_name="Теги",
            ),
        ),
    ]
