# Generated by Django 4.2.3 on 2023-07-30 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                through="articles.Scope", to="articles.tag", verbose_name="Теги"
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scopes",
                to="articles.tag",
            ),
        ),
    ]
