# Generated by Django 4.2.3 on 2023-07-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0004_alter_article_tags_alter_scope_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                related_name="article",
                through="articles.Scope",
                to="articles.tag",
                verbose_name="Теги",
            ),
        ),
        migrations.AlterField(
            model_name="scope",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="articles.tag"
            ),
        ),
    ]
