# Generated by Django 4.2.4 on 2023-08-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement_favorites_alter_advertisement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=6),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
