# Generated by Django 4.2.3 on 2023-07-30 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("school", "0003_remove_student_teacher_student_teacher"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="teacher",
        ),
        migrations.AddField(
            model_name="student",
            name="teachers",
            field=models.ManyToManyField(
                related_name="students", to="school.teacher", verbose_name="Учитель"
            ),
        ),
    ]
